name: router_pro
description: Flutter routing and lifecycle toolkit with launch modes, guards, drawer stacks, and visibility awareness.
version: 0.2.1
homepage: https://github.com/zhengzaihong/router_lifecycle


platforms:
  windows:
  web:
  android:
  linux:
  ios:
  macos:

environment:
  sdk: ">=2.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: false
